name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk
        pip install --upgrade pip
        pip install buildozer cython virtualenv 

    - name: Build APK
      run: |
        buildozer android debug
        mv bin/*.apk app.apk

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Android-APK
        path: app.apk
